---
# file: webserver.yml
- user:
    name: ghost-admin
    shell: /bin/bash
    groups: sudo

# Install apt packages.
- name: Install Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
  - nginx
  - python-mysqldb
  - mysql-server
  # Needed for pip.
  - python-pip

# Install MySQL Python with pip.
- name: Install the MySQL-python module
  pip: name=MySQL-python
- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

# Set the root password.
- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 
