name: Build & Deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.61.0'
        # extended: true

    - name: Build
      working-directory: ./dwmkerr.com
      run: hugo --minify

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: ./dwmkerr.com/public
