# The 'release-please' workflow is used to create the 'Release Please' pull
# request. This PR is opened when we have a new commit to main.
# See:
#   https://github.com/googleapis/release-please
name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:

    runs-on: ubuntu-20.04

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: dwmkerr.com

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.93.0'
          # extended: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        working-directory: ./dwmkerr.com
        run: hugo --minify
        if: ${{ steps.release.outputs.release_created }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dwmkerr.com/public
        if: ${{ steps.release.outputs.release_created }}
