name: Validate Pull Request

# This workflow verifies that the site will build for pull requests.
on: [pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
      if: ${{ steps.release.outputs.release_created }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.93.0'
        # extended: true
      if: ${{ steps.release.outputs.release_created }}

    - name: Build
      working-directory: ./dwmkerr.com
      run: hugo --minify
      if: ${{ steps.release.outputs.release_created }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dwmkerr.com/public
      if: ${{ steps.release.outputs.release_created }}
